"""Initial migration

Revision ID: 4a789501fd0d
Revises: 
Create Date: 2026-08-28 07:55:01.002953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a789501fd0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'member', name='roleenum'), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alert_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.Enum('dingtalk', 'wecom', 'email', name='channeltypeenum'), nullable=False),
    sa.Column('config_ciphertext', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_channels_id'), 'alert_channels', ['id'], unique=False)
    op.create_table('monitored_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('domain', 'email', 'username', 'password', 'api_key', name='assettypeenum'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('value_ciphertext', sa.String(), nullable=True),
    sa.Column('value_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', name='assetstatusenum'), nullable=True),
    sa.Column('is_domain_verified', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_assets_id'), 'monitored_assets', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_assets_value_hash'), 'monitored_assets', ['value_hash'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('hibp_breach', 'hibp_paste', 'hibp_stealer_log', 'pwned_password', name='findingsourceenum'), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('raw_data_json', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['monitored_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_external_ref'), 'findings', ['external_ref'], unique=False)
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['alert_channels.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_external_ref'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_monitored_assets_value_hash'), table_name='monitored_assets')
    op.drop_index(op.f('ix_monitored_assets_id'), table_name='monitored_assets')
    op.drop_table('monitored_assets')
    op.drop_index(op.f('ix_alert_channels_id'), table_name='alert_channels')
    op.drop_table('alert_channels')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
