"""Add HibpConfig and BreachCatalog

Revision ID: 9e1d59d16db8
Revises: 4a789501fd0d
Create Date: 2026-08-28 08:15:19.991136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1d59d16db8'
down_revision: Union[str, Sequence[str], None] = '4a789501fd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breach_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('breach_date', sa.String(), nullable=True),
    sa.Column('added_date', sa.String(), nullable=True),
    sa.Column('pwn_count', sa.Integer(), nullable=True),
    sa.Column('data_classes_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_catalog_id'), 'breach_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_breach_catalog_name'), 'breach_catalog', ['name'], unique=True)
    op.create_table('hibp_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_ciphertext', sa.String(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hibp_config_id'), 'hibp_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hibp_config_id'), table_name='hibp_config')
    op.drop_table('hibp_config')
    op.drop_index(op.f('ix_breach_catalog_name'), table_name='breach_catalog')
    op.drop_index(op.f('ix_breach_catalog_id'), table_name='breach_catalog')
    op.drop_table('breach_catalog')
    # ### end Alembic commands ###
